name: Update external doc?

on:
  pull_request_target:
    types: [opened, synchronize]
    branches: [ main ]

jobs:
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    permissions:
        issues: write
        pull-requests: write
        contents: read
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize' }}
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Get files linked to external doc
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: |
            content/guides/astro.md
      - name: Create issue
        id: create-issue
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_NUMBER: ${{ github.event.number }}
          CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/external-doc-issue.yml
          assignees: ${{ github.event.pull_request.user.login }}
          update_existing: false
          search_existing: all     
      - name: Comment PR
        if: github.run_number == 1 && steps.changed-files-specific.outputs.any_changed == 'true' && steps.create-issue.outcome != 'success'
        env:
          CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.pull_request.number;
            const message = `You updated ${{ env.CHANGED_FILES }}. This content is also listed on external doc. Issue number ${{ steps.create-issue.outputs.number }} has been created has been created and asigned to you ğŸ«µğŸ‘ï¸ğŸ‘„ğŸ‘ï¸
            
            See it or modify it here: ${{ steps.create-issue.outputs.url }}
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message
                });
      
